[package]
name = "psst-gui"
version = "0.1.0"
authors = ["Jan Pochyla <jpochyla@gmail.com>"]
edition = "2018"

[dependencies]
psst-core = { path = "../psst-core" }

aspotify = { git = "https://github.com/jpochyla/aspotify", branch = "explicit_access_token" }
chrono = "0.4.19"
# druid = { git = "https://github.com/xi-editor/druid", features = ["im", "image"] }
druid = { git = "https://github.com/jpochyla/druid", features = ["im", "image"], branch = "textbox-options" }
env_logger = "0.7"
image = "0.23"
itertools = "0.9"
log = "0.4"
lru-cache = "0.1"
reqwest = { version = "0.10" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "0.2", features = ["full", "sync"] }
