[package]
name = "psst-bin"
version = "0.1.0"
authors = ["Jan Pochyla <jpochyla@gmail.com>"]
edition = "2018"

[dependencies]
psst-core = { path = "../psst-core" }

env_logger = "0.7.1"
log = "0.4.8"
quick-protobuf = "0.8.0"